/**
 * Builds extension/src/ui/shared/icons.js from the local Iconsax SVG set.
 *
 *   node tools/build-icons.mjs [path-to-iconsax/All] [style]
 *
 * Defaults: C:/Users/alireza/Desktop/Svg/All, style "linear". Colours are
 * rewritten to currentColor so icons follow the surrounding text colour.
 * Add a name to ICONS below and re-run to ship another icon.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const SOURCE = process.argv[2] ?? 'C:/Users/alireza/Desktop/Svg/All';
const STYLE = process.argv[3] ?? 'linear';
const OUT = resolve(import.meta.dirname, '../extension/src/ui/shared/icons.js');

/** UI name -> Iconsax file name. */
const ICONS = {
  brand: 'flash',
  undo: 'undo',
  redo: 'redo',
  desktop: 'monitor',
  tablet: 'devices',
  mobile: 'mobile',
  validate: 'tick-circle',
  save: 'save-2',
  version: 'tag',
  projects: 'folder-2',
  export: 'document-download',
  close: 'close-circle',
  trash: 'trash',
  restore: 'refresh-left-square',
  ok: 'tick-circle',
  error: 'close-circle',
  warning: 'warning-2',
  info: 'info-circle',
  pick: 'gps',
  builder: 'element-3',
  // structure tree
  container: 'element-4',
  heading: 'text',
  'text-editor': 'textalign-left',
  image: 'gallery',
  button: 'mouse-square',
  video: 'video-play',
  icon: 'star',
  form: 'sms',
  'nav-menu': 'menu',
  'icon-list': 'task-square',
  widget: 'box',
  native: 'flash',
  chevron: 'arrow-right-3',
  'chevron-down': 'arrow-down-1',
  global: 'global',
  // about section
  about: 'info-circle',
  website: 'global',
  github: 'code-circle',
  issue: 'message-question',
  telegram: 'send-2',
  'external-link': 'export',
};

const entries = Object.entries(ICONS).map(([name, file]) => {
  const raw = readFileSync(join(SOURCE, STYLE, `${file}.svg`), 'utf8');
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/#292D32/gi, 'currentColor')
    .replace(/\s*\n\s*/g, '')
    .trim();
  return `  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`;
});

writeFileSync(OUT, `/**
 * UI icons — Iconsax (${STYLE}), generated by tools/build-icons.mjs.
 * Do not edit by hand: add the name to the generator and re-run it.
 */

import { setSafeHTML } from '../../common/safe-html.js';

const PATHS = {
${entries.join('\n')}
};

/**
 * Inline SVG markup for an icon.
 * @param {string} name key of PATHS
 * @param {object} [opts] { size = 18, className = '' }
 */
export function icon(name, { size = 18, className = '' } = {}) {
  const body = PATHS[name] ?? PATHS.widget;
  return \`<svg class="ef-icon\${className ? \` \${className}\` : ''}" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false">\${body}</svg>\`;
}

/** Fill every \`<… data-icon="name">\` placeholder under \`root\`. */
export function hydrateIcons(root = document) {
  for (const el of root.querySelectorAll('[data-icon]')) {
    const size = Number(el.getAttribute('data-icon-size')) || undefined;
    setSafeHTML(el, icon(el.getAttribute('data-icon'), { size }));
  }
}

export const ICON_NAMES = Object.keys(PATHS);
`);
console.log(`wrote ${OUT} (${entries.length} icons, ${STYLE})`);
